### ISSUE TITLE
Installation failure: FATAL: Profile script not found.

### ISSUE THREAD

**Issue by pathikrit** [twolfson/sexy-bash-prompt#62] opened 2016-06-07 20:55 UTC
```shell
bash-4.3$ (cd /tmp && git clone --depth 1 https://github.com/twolfson/sexy-bash-prompt && cd sexy-bash-prompt && make install) && source ~/.bashrc
Cloning into 'sexy-bash-prompt'...
remote: Counting objects: 330, done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 330 (delta 31), reused 310 (delta 30), pack-reused 0
Receiving objects: 100% (330/330), 121.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (31/31), done.
Checking connectivity... done.
# Copying .bash_prompt to ~/.bash_prompt
cp -f ".bash_prompt" "/Users/pbhowmick/.bash_prompt"
./install.bash
# Adding ~/.bash_prompt to ~/.bashrc
FATAL: Profile script not found.
make: *** [install] Error 1
```

**Comment by twolfson** [comment] 2016-06-07 22:39
This is a duplicate of #51, please see it for an explanation and solution.

**Closed by twolfson** 2016-06-07 22:39 UTC
