### ISSUE TITLE
Weird display inside Docker container

### ISSUE THREAD

**Issue by mthmulders** [twolfson/sexy-bash-prompt#50] opened 2015-02-02 14:03 UTC
I'm trying to use the sexy prompt inside a Docker container, but the icons display rather weird:

    $ . ~/.bash_prompt 
    <user>@3a4ffe9e19de:~/git/project on master���  

Note that I've tweaked the first part of the prompt a bit, but the last parts should be unchanged. When I ssh into the host machine it displays just fine (and it uses the exact same `PS1`). I'm running XFCE4 Terminal inside the Docker image.

Any thoughts what might be wrong?

**Comment by twolfson** [comment] 2015-02-02 18:01
I have had display issues in the `tty` emulators (e.g. `getty` via `Ctrl+Alt+F1`), #41. The workaround there was to introduce symbol overriding.

https://github.com/twolfson/sexy-bash-prompt/tree/0.24.2#symbols

I am not going to close this issue immediately because I would like to try to reproduce as well. However, that should get you back on the right track.

**Comment by twolfson** [comment] 2015-02-03 03:31
I have taken a look at this and verified it is the same issue as #41. It looks like the symbols from the README won't work so I made an even simpler format:

```bash
PROMPT_SYNCED_SYMBOL=""
PROMPT_DIRTY_SYNCED_SYMBOL="*"
PROMPT_UNPUSHED_SYMBOL="^"
PROMPT_DIRTY_UNPUSHED_SYMBOL="*^"
PROMPT_UNPULLED_SYMBOL="v"
PROMPT_DIRTY_UNPULLED_SYMBOL="*v"
PROMPT_UNPUSHED_UNPULLED_SYMBOL="*^v"
PROMPT_DIRTY_UNPUSHED_UNPULLED_SYMBOL="*^v"
```

![selection_016](https://cloud.githubusercontent.com/assets/902488/6014035/b7a11b28-ab22-11e4-8ec0-724616f12710.png)

I have a feeling that we can also resolve the issue by adding fonts that support the `sexy-bash-prompt` symbols and configuring `xfce4-terminal` to use those.

For reference, these are the steps I used to reproduce:

http://catch-0x16.blogspot.com/2014/09/docker-with-x-forwarding.html

to set up X11 forwarding which was where we encountered the original issue.

```bash
# After following article
# Log in as root
docker run -i -t --rm \
  -e DISPLAY=$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  "$@" ubuntu-x11 bash

# Install `xfce4-terminal` and `sexy-bash-prompt` dependencies
apt-get install -y xfc4-terminal git make

# Log in as our user
su todd --login

# Install `sexy-bash-prompt` via one-liner
(cd /tmp && git clone --depth 1 https://github.com/twolfson/sexy-bash-prompt && cd sexy-bash-prompt && make install) && source ~/.bashrc

# Launch `xfce4-terminal` with X11 forwarding
xfce4-terminal &

# Navigate to demo directories
cd /tmp/sexy-bash-prompt/
make demo
# Run demo scripts
```

![selection_015](https://cloud.githubusercontent.com/assets/902488/6014018/82da950e-ab22-11e4-95b6-b6634da3e0e9.png)

**Closed by twolfson** 2015-02-03 03:31 UTC

**Comment by mthmulders** [comment] 2015-02-03 07:12
Thanks, didn't realize it was the same as #41. Will go for that solution!
