### ISSUE TITLE
Consolidate invocations of git rev-parse

### ISSUE THREAD

**Issue by rpdelaney** [twolfson/sexy-bash-prompt#32] opened 2014-03-14 19:40 UTC
We call `git rev-parse` with `is_on_git()` and then call it again with `get_git_progress()`. These functions can be combined to avoid duplicating the slow (possibly very slow) work of searching back up the tree.

**Comment by twolfson** [comment] 2019-03-01 21:52
We haven't talked about this issue in almost 5 years. In my opinion, this is an ease of maintenance trade-off with a performance one. Is this still an issue? Can we close it?

**Comment by rpdelaney** [comment] 2019-03-02 02:26
IIRC this was a problem for me when I was using cygwin. Performance is still an issue when working on git repos over sshfs. But I don't have either use case anymore so I'm not working on it, yeah. I think it's still a thing and it would be nice to be better at that, but I wouldn't expect much from me on it. Up to you.

**Comment by twolfson** [comment] 2019-03-02 07:01
Going to close this due to nobody else having similar complaints. I think at its core, the issue is we're trying to use `git`, which is heavily file and process based, in a scenario which doesn't perform well with such constraints. In the future, I'd prob recommend people to switch prompts in these scenarios =/

**Closed by twolfson** 2019-03-02 07:01 UTC
Labels: enhancement
