### ISSUE TITLE
rename to "Extravagant Bash Prompt"

### ISSUE THREAD

**Issue by whit537** [twolfson/sexy-bash-prompt#56] opened 2015-11-06 21:35 UTC
Greetings, @twolfson, et al.! :-)

I'm visiting from https://github.com/gratipay/team-review/issues/107, where we're discussing whether `sexy-bash-prompt` is a project we want to accept as a Team on Gratipay. We're stumbling on the name, to be honest. "Sexy," while obviously not an *egregiously* sexist term, does seem to contribute somewhat to a sexualized tech culture that is generally alienating to women—something we at Gratipay would prefer to avoid endorsing.

@twolfson commented over there:

> To provide info from my perspective, the initial script wasn't written by me but I wound up formalizing it into a repo:
>
https://gist.github.com/gf3/306785/a35d28b6bdd0f7c54318cce510738438f04dabaa
>
That's the "Forked from a gist by gf3." on the README. I was hesitant about keeping the name (for similar reasons as listed above) but I kept it consistent for easier discovery.
>
I think at this point it might be a large blow to the awareness of the repo since this isn't a copy change but a change to the repository's handle =/

Fair enough. As mentioned, GitHub does [offer repo redirects](https://github.com/blog/1508-repository-redirects-are-here) now, so that in itself needn't be a worry. Furthermore, the original script from Steve Losh is called "Extravagant Zsh Prompt," so if you rename this project to "Extravagant Bash Prompt," you'll in fact be more closely aligning yourselves with Steve's original project, which could *improve* discovery. ;-)

@twolfson, et al. Waddya think? Are you willing to rename to "Extravagant Bash Prompt"? :-)

**Comment by twolfson** [comment] 2015-11-07 03:32
To reiterate my stance on this: while we are regretably aware of the implicit connotations (and have been since the inception), I would prefer not to alter the name since it will damage existing page rankings =/

With respect to the suggestion of "Extravagant Bash Prompt", I would prefer to avoid it since we aren't 1:1 with it (nor do we want to be a duplicate of it). Thanks for the idea though =)

@rpdelaney What are your thoughts? Abstaining is perfectly fine as well.

**Comment by rpdelaney** [comment] 2015-11-07 07:00
I'm sympathetic to the ethical issues raised by @whit537 . If possible, it may be worthwhile to confirm whether a redirect would preserve existing pagerank. Also, consider the unknown extent to which the name may have prevented it from being promoted elsewhere.

I googled "Extravagant Bash Prompt" and got a bunch of hits about "Extravagant Zsh Prompt". I'd suggest exploring whether another compromise can be found.

**Comment by twolfson** [comment] 2015-11-07 23:24
Here are some statistics:

In an incognito Chrome window from Chicago, IL we are page rank 5 in Google for "bash prompt".

We got 304 unique visitors within the past 2 weeks via that.

![selection_190](https://cloud.githubusercontent.com/assets/902488/11017880/5c589fd4-8574-11e5-8fb4-808638a38b80.png)

![selection_191](https://cloud.githubusercontent.com/assets/902488/11017881/60273efe-8574-11e5-8797-91786772bddf.png)

From my SEO knowledge, changing the name will break existing back links and decrease that page rank.

I should also mention that I have had personal frustrations when projects I have used change names (e.g. `atom-shell` to `electron`, Gittip to Gratipay). It makes updating existing documentation annoying (I still have plenty of Gittip links in my repos) and finding existing documenting frustrating (e.g. had to double search for `atom-shell` and `electron`).

One question I want to get answered by @whit537 is: If we were to change `sexy-bash-prompt's` name, another repo were to come along after us with a similar setup (e.g. `sexy-database-repl`), and they were strongly opposed to change their name. Would Gratipay still let them in as a team or not?

**Comment by whit537** [comment] 2015-11-12 13:41
Fair question, re-raised on https://github.com/gratipay/team-review/issues/107.

**Comment by f4w5yhq6z7bo** [comment] 2015-11-13 00:17
Kind of misogynistic and heteronormative for @whit537 to assume that "sexy" refers to a woman in the first place, without asking.

**Comment by twolfson** [comment] 2015-11-13 00:21
Removed unconstructive comment from someone's throwaway account

**Comment by f4w5yhq6z7bo** [comment] 2015-11-13 09:48
This is my main account, and I believe calling out hypocrisy to be incredibly constructive.

**Comment by twolfson** [comment] 2015-11-13 18:11
@whit537 never directly attached the term "sexy" to women. He said that it alters the perceived environment which may alienate women. Both @rpdelaney and myself agreed that this is a possible scenario.

On a tangent, @whit537 didn't mention that "sexy" can alienate non-female persons as well. But the majority of tech is men so we should be focusing on the minorities. As for transgender and non-prescriptive genders, it's a shame we don't directly mention them in this discussion but I believe @whit537 had good intent.

With respect to the main thread, my stance has been "prefer not to change things due to damaging SEO-like reputation". Although as we talk through these issues, I am starting to lean towards a rename.

-------

Since these comments are pulling away from the main thread, I will be deleting them once again.

**Comment by webmaven** [comment] 2015-11-23 14:58
[according to Matt Cuts](https://www.youtube.com/watch?v=Filv4pP-1nw), SEO shouldn't be *much* affected if GitHub implemented this correctly: https://github.com/blog/1508-repository-redirects-are-here

I have an inquiry in to GH support to ask for more details on how they are doing the redirects, and what empirical effect they see on PageRank.

Nevertheless, some SEO rank would certainly be lost, at least temporarily, but from looking at the rank of the other results on the 1st and 2nd SERP, it does not seem that PageRank itself is the dominant factor in SERP position for that search (I see a lot of 0s, 3s, and 4s, both above and below you).

Will report back with more info once I hear from GH.

- Michael

**Comment by webmaven** [comment] 2015-11-23 15:25
@twolfson:

> With respect to the suggestion of "Extravagant Bash Prompt", I would prefer to avoid it since we aren't 1:1 with it (nor do we want to be a duplicate of it). Thanks for the idea though =)

If 'Extravagant' doesn't suit, would it be helpful to suggest other superlatives here?

**Comment by twolfson** [comment] 2015-11-23 18:34
I think we will eventually update the name. Unfortunately, there's more to be done than a GitHub rename (e.g. update README, update screenshots, rename Twitter handle, update Twitter/Google alerts, contemplate updating blog posts).

Additionally, I am about to be more AFK than not for the next 2 weeks.

Thanks for your willingness to help though =)

**Comment by webmaven** [comment] 2015-11-23 19:19
You are very welcome. If you do create a renaming ticket, please @ mention me, and I'll do my best to help find a good new name.

**Comment by CronosDage** [comment] 2015-12-04 23:21
>[The word] "sexy" (...) does seem to contribute somewhat to a sexualized tech culture that is generally alienating to women.

What.

**Comment by twolfson** [comment] 2016-10-12 11:12
Revisiting this 1 year later, deciding to still not rename repository. Closing issue for now

**Closed by twolfson** 2016-10-12 11:12 UTC
